import { StyleSheet } from 'react-native';

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    paddingVertical: 40, 
  },
  optionContainer: {
    width: '80%', 
    alignItems: 'center',
    marginVertical: 10, 
    position: 'relative', 
  },
  innerContainer: {
    alignItems: 'center',
  },
  tickContainer: {
    width: 120,
    height: 120,
    borderRadius: 60, 
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'white',
    shadowColor: 'rgba(0, 0, 0, 0.24)',
    shadowOffset: { width: 3, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 15, 
  },
  tickContainer2: {
    width: 120,
    height: 120,
    borderRadius: 60, 
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'orange',
    shadowColor: 'rgba(0, 0, 0, 0.24)',
    shadowOffset: { width: 3, height: 5 },
    shadowOpacity: 0.5,
    shadowRadius: 10,
    elevation: 5,
    marginBottom: 15, 
  },
  tickImage: {
    width: 90,
    height: 90,
    resizeMode: 'contain',
  },
  puntitosMascotero: {
    position: 'absolute',
    top: -50, 
    left: 90, 
    width: 175,
    height: 160,
  },
  puntitosProtectora: {
    position: 'absolute',
    bottom: -50, 
    left: 50, 
    width: 175,
    height: 160,
  },
  tituloMascotero: {
    fontSize: 18,
    fontWeight: '400',
    color: 'black', 
    marginBottom: "10px",
  },
  tituloProtectora: {
    fontSize: 18,
    fontWeight: '400',
    color: 'black',
    marginBottom: "10px",
    marginRight: "20px",
  },
});
